# Getting Started with DataJoint

In [1]:
import datajoint as dj

## Creating your first schema

In [3]:
schema = dj.schema('university')

Connecting shanshen@localhost:3306

## Creating your first table

In [4]:
@schema
class Student(dj.Manual):
    definition = """
    student_id : int unsigned   # university-wide ID number
    ---
    first_name      : varchar(40)
    last_name       : varchar(40)
    sex             : enum('F', 'M', 'U')
    """

### Inserting an entry as a dictionary

In [5]:
Student.insert1({
    'student_id': 1, 
    'first_name': 'Alice', 
    'last_name': 'Anderson', 
    'sex': 'F'})

In [6]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
 (1 tuples)

### Inserting an entry as a tuple

In [7]:
Student.insert1((2, 'Bob', 'Dylan', 'M'))

In [8]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
2              Bob            Dylan         M
 (2 tuples)

In [9]:
Student.insert1((3, 'Carol', 'Lewis', 'F'))

In [10]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
2              Bob            Dylan         M
3              Carol          Lewis         F
 (3 tuples)

### Inserting multiple entries as a list of dictionaries

In [ ]:
students = [
    {'student_id': 4, 'first_name': 'Chris', 'last_name': 'Smith', 'sex': 'M'},
    {'student_id': 5, 'first_name': 'Stella', 'last_name': 'Taylor', 'sex': 'F'},
    {'student_id': 6, 'first_name': 'Max', 'last_name': 'Scott', 'sex': 'M'}
]
Student.insert(students)

In [ ]:
Students()

### Inserting multiple entries as a list of tuples

In [ ]:
students = [
    (7, 'John', 'Allen', 'M'),
    (8, 'Julia', 'White' 'F'),
    (9, 'Emma', 'Reed', 'F')
]
Student.insert(students)

In [ ]:
Students()

### Dropping a table

In [8]:
Student.drop()

`university`.`student` (300 tuples)
Tables dropped.  Restart kernel.

In [4]:
@schema
class Student(dj.Manual):
    definition = """
    student_id : int unsigned   # university-wide ID number
    ---
    first_name      : varchar(40)
    last_name       : varchar(40)
    sex             : enum('F', 'M', 'U')
    date_of_birth   : date
    home_address    : varchar(120) # mailing street address
    home_city       : varchar(60)  # mailing address
    home_state      : char(2)      # US state acronym: e.g. OH
    home_zip        : char(10)     # zipcode e.g. 93979-4979
    home_phone      : varchar(20)  # e.g. 414.657.6883x0881
    """

In [5]:
import insert_students

In [6]:
insert_students.insert(Student, 300)

In [5]:
Student()

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
0              David          Cochran       M       1999-03-12     3750 Johnson V East Johnnyton CO             31392        +1-935-030-104
1              Jessica        Watson        F       1998-11-20     2641 Powell By East Savannah  MN             31359        +1-083-014-988
2              Gregg          Long          M       1994-10-24     101 Thomas Cre Port Curtisbur ID             01061        (047)303-8162
3              Kevin          Young         M       1991-08-22     03070 Ashley P Johnhaven      IL             95869        +1-718-791-793
4              Ann            Miller        F       2001-06-17     9716 Henderson South Russell  IL             08167        (492)097-6211x
5              Thomas         Cordova       M       1984-11-10     5447 Jacquelin Rossbury       KS             92635        (255)967-8834
6              Joseph         Thomas        M       1987-10-16     69328 Alexande Monicaberg     AL             78551        001-736-640-89
   ...
 (300 tuples)

## Querying data

### Restricting by attribute values

In [8]:
Student() & 'sex="F"'

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
1              Jessica        Watson        F       1998-11-20     2641 Powell By East Savannah  MN             31359        +1-083-014-988
4              Ann            Miller        F       2001-06-17     9716 Henderson South Russell  IL             08167        (492)097-6211x
7              Colleen        Russell       F       2001-12-17     549 Kimberly M Amandahaven    MN             14981        336.611.0538x8
9              Rebecca        Bradford      F       1988-03-07     889 David Exte East Jeffreych KY             44023        001-977-286-32
14             Elizabeth      Cook          F       1987-11-19     269 Miller Way Reedfurt       MI             02116        (154)889-2148x
17             Jennifer       Rios          F       1999-09-13     878 Wendy Isle Aguilartown    TX             49117        634.512.4199x3
18             Kayla          Underwood     F       1996-08-04     863 Hobbs Lock Lake Cheyennet IL             43023        562-605-0117
   ...
 (146 tuples)

In [19]:
Student() & 'date_of_birth > "2000-01-01"'

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
4              Ann            Miller        F       2001-06-17     9716 Henderson South Russell  IL             08167        (492)097-6211x
7              Colleen        Russell       F       2001-12-17     549 Kimberly M Amandahaven    MN             14981        336.611.0538x8
15             Adam           Lane          M       2003-07-25     585 Roberts Tu Coreyfurt      WI             75990        393.081.7003x9
16             William        Ramirez       M       2001-11-17     6817 Brittany  Kimberlyland   AL             45400        +1-890-338-179
21             Nicole         Steele        F       2002-07-26     2600 Rich Traf Kevinmouth     AL             08179        096.342.1859x4
22             Travis         Garcia        M       2003-01-27     0356 Myers Pla North Martinch TN             61026        001-637-627-23
30             Courtney       Henry         F       2004-02-05     429 James Shoa South Dawnberg ME             85208        338.158.3296x5
   ...
 (75 tuples)

In [20]:
female_texans = Student & {'sex': 'F', 'home_state': 'TX'}

In [9]:
female_texans

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
17             Jennifer       Rios          F       1999-09-13     878 Wendy Isle Aguilartown    TX             49117        634.512.4199x3
81             Traci          Miller        F       1993-02-28     5483 Morris Ga Martinezside   TX             33581        185.066.6296
110            Judy           Howell        F       1995-06-25     28026 King Fla Melissafort    TX             68149        4825193373
173            Jessica        Sosa          F       1999-11-03     69050 Anthony  West Frank     TX             00894        001-319-684-98
247            Debra          Buchanan      F       1990-02-09     789 Little Bur Port Victormou TX             92941        001-950-970-47
 (5 tuples)

## Fetching data from the querying results

In [21]:
female_texans.fetch()

array([( 17, 'Jennifer', 'Rios', 'F', datetime.date(1999, 9, 13), '878 Wendy Isle', 'Aguilartown', 'TX', '49117', '634.512.4199x3582'),
       ( 81, 'Traci', 'Miller', 'F', datetime.date(1993, 2, 28), '5483 Morris Gardens', 'Martinezside', 'TX', '33581', '185.066.6296'),
       (110, 'Judy', 'Howell', 'F', datetime.date(1995, 6, 25), '28026 King Flat', 'Melissafort', 'TX', '68149', '4825193373'),
       (173, 'Jessica', 'Sosa', 'F', datetime.date(1999, 11, 3), '69050 Anthony Alley Apt. 347', 'West Frank', 'TX', '00894', '001-319-684-9826x633'),
       (247, 'Debra', 'Buchanan', 'F', datetime.date(1990, 2, 9), '789 Little Burg Suite 960', 'Port Victormouth', 'TX', '92941', '001-950-970-4775x522')],
      dtype=[('student_id', '<i8'), ('first_name', 'O'), ('last_name', 'O'), ('sex', 'O'), ('date_of_birth', 'O'), ('home_address', 'O'), ('home_city', 'O'), ('home_state', 'O'), ('home_zip', 'O'), ('home_phone', 'O')])

In [22]:
female_texans.fetch(as_dict=True)

[OrderedDict([('student_id', 17),
              ('first_name', 'Jennifer'),
              ('last_name', 'Rios'),
              ('sex', 'F'),
              ('date_of_birth', datetime.date(1999, 9, 13)),
              ('home_address', '878 Wendy Isle'),
              ('home_city', 'Aguilartown'),
              ('home_state', 'TX'),
              ('home_zip', '49117'),
              ('home_phone', '634.512.4199x3582')]),
 OrderedDict([('student_id', 81),
              ('first_name', 'Traci'),
              ('last_name', 'Miller'),
              ('sex', 'F'),
              ('date_of_birth', datetime.date(1993, 2, 28)),
              ('home_address', '5483 Morris Gardens'),
              ('home_city', 'Martinezside'),
              ('home_state', 'TX'),
              ('home_zip', '33581'),
              ('home_phone', '185.066.6296')]),
 OrderedDict([('student_id', 110),
              ('first_name', 'Judy'),
              ('last_name', 'Howell'),
              ('sex', 'F'),
              ('date_of_birth', datetime.date(1995, 6, 25)),
              ('home_address', '28026 King Flat'),
              ('home_city', 'Melissafort'),
              ('home_state', 'TX'),
              ('home_zip', '68149'),
              ('home_phone', '4825193373')]),
 OrderedDict([('student_id', 173),
              ('first_name', 'Jessica'),
              ('last_name', 'Sosa'),
              ('sex', 'F'),
              ('date_of_birth', datetime.date(1999, 11, 3)),
              ('home_address', '69050 Anthony Alley Apt. 347'),
              ('home_city', 'West Frank'),
              ('home_state', 'TX'),
              ('home_zip', '00894'),
              ('home_phone', '001-319-684-9826x633')]),
 OrderedDict([('student_id', 247),
              ('first_name', 'Debra'),
              ('last_name', 'Buchanan'),
              ('sex', 'F'),
              ('date_of_birth', datetime.date(1990, 2, 9)),
              ('home_address', '789 Little Burg Suite 960'),
              ('home_city', 'Port Victormouth'),
              ('home_state', 'TX'),
              ('home_zip', '92941'),
              ('home_phone', '001-950-970-4775x522')])]

In [12]:
female_texans.fetch(format="frame")

TypeError: __call__() got an unexpected keyword argument 'format'

In [14]:
len(female_texans)

5

In [29]:
utahns = Student & {'home_state': 'UT'}

In [33]:
utah_genz = utahns & 'date_of_birth > "1989-01-01"'

In [34]:
utah_genz

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
27             Steven         Lewis         M       1990-02-12     06471 Tanner P Chloetown      UT             38356        (180)010-0231
92             Brittany       Hampton       F       1994-01-26     954 Shaun Bypa Hartmanchester UT             15590        (073)949-5017
240            Christina      Ward          F       1992-08-13     46122 Maddox L East Cody      UT             19865        001-462-098-30
 (3 tuples)

In [35]:
utah_genz = utah_genz.proj('last_name', 'home_city','home_state','sex')
utah_genz

*student_id    last_name     home_city      home_state     sex
+------------+ +-----------+ +------------+ +------------+ +-----+
27             Lewis         Chloetown      UT             M
92             Hampton       Hartmanchester UT             F
240            Ward          East Cody      UT             F
 (3 tuples)

In [36]:
for r in utah_genz:
    print(r)

OrderedDict([('student_id', 27), ('last_name', 'Lewis'), ('home_city', 'Chloetown'), ('home_state', 'UT'), ('sex', 'M')])
OrderedDict([('student_id', 92), ('last_name', 'Hampton'), ('home_city', 'Hartmanchester'), ('home_state', 'UT'), ('sex', 'F')])
OrderedDict([('student_id', 240), ('last_name', 'Ward'), ('home_city', 'East Cody'), ('home_state', 'UT'), ('sex', 'F')])